dubbo:
  application:
    name: dubbo-provider
  registry:
    address: 224.5.6.7:1234
    # 读者请自行更改zookeeper地址
    protocol: multicast
    check: false
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000

server:
  port: 8061
